# Generated by Django 3.0.5 on 2020-04-23 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_auto_20200423_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
